# Generated by Django 2.2.4 on 2019-08-08 17:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('WISHLIST', 'WISHLIST'), ('MAGAZIN', 'MAGAZIN')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(default=datetime.datetime(2019, 8, 8, 17, 50, 13, 88260, tzinfo=utc))),
                ('to_date', models.DateField()),
                ('list', models.ManyToManyField(to='wishlist.List')),
                ('product', models.ManyToManyField(to='wishlist.Products')),
            ],
        )
    ]
