# Generated by Django 2.2.4 on 2019-08-08 17:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricehistory',
            name='list',
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='price',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='from_date',
            field=models.DateField(default=datetime.datetime(2019, 8, 8, 17, 57, 20, 105959, tzinfo=utc)),
        ),
    ]
