# Generated by Django 2.2.4 on 2019-08-08 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0006_auto_20190808_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricehistory',
            name='from_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
