# Generated by Django 2.2.4 on 2019-08-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0008_list_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricehistory',
            name='to_date',
        ),
        migrations.AlterField(
            model_name='list',
            name='type',
            field=models.CharField(choices=[('WISHLIST', 'WISHLIST'), ('MAGAZIN', 'MAGAZIN'), ('CATEGORY', 'CATEGORY')], max_length=10),
        ),
    ]
