# Generated by Django 2.2.4 on 2019-08-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0009_auto_20190810_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='list',
            field=models.ManyToManyField(to='wishlist.List'),
        ),
    ]
