# Generated by Django 2.2.4 on 2019-08-10 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0010_products_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricehistory',
            name='product',
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='wishlist.Products'),
            preserve_default=False,
        ),
    ]
