# Generated by Django 2.2.4 on 2019-08-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0011_auto_20190810_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricehistory',
            name='from_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
