# Generated by Django 2.2.4 on 2019-08-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0013_auto_20190810_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='wished_product',
            field=models.IntegerField(default=0),
        ),
    ]
